using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SocialWorkouts.ApplicationDb.Models;
using SocialWorkouts.Services;

namespace SocialWorkouts.Controllers;

[ApiController]
[Route("[controller]")]
public class TrainerController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<TrainerController> _logger;

    public TrainerController(ILogger<TrainerController> logger, ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    /// <summary> Adds a new trainer to the db.</summary>
    /// <remarks>  NOTE: You must not provide an id, the database will automatically generate one for you.</remarks>
    /// <param name="trainer">The trainer to add</param>
    /// <returns>The newly added trainer</returns>
    /// <response code="201">Returns the newly added trainer</response>
    /// <response code="400">The trainer's password is blank</response>
    [HttpPost]
    public async Task<ActionResult<TrainerEntity>> Create(TrainerEntity trainer)
    {
        if (trainer.Id != null) return BadRequest("You cannot specify an id for a trainer, it is generated by the database");
        else if (string.IsNullOrWhiteSpace(trainer.Password)) return BadRequest("You must provide a valid password");
        await _context.Trainer.AddAsync(trainer);
        await _context.SaveChangesAsync();
        return CreatedAtAction("Create", trainer);
    }
}